CREATE TABLE IF NOT EXISTS type (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, path TEXT, type_id INTEGER, FOREIGN KEY (type_id) REFERENCES type(id));
